default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: tv_development


test:
  <<: *default
  database: tv_test
 # production:
#adapter: postgresql
#encoding: unicode
# For details on connection pooling, see Rails configuration guide
# https://guides.rubyonrails.org/configuring.html#database-pooling
#pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#database: sample_app_production
#username: sample_app
#password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
#
production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>